## import the libiaries

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
data= pd.read_csv("electronics_product.csv")

In [19]:
data

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,0,"Redmi 10 Power (Power Black, 8GB RAM, 128GB St...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81eM15lVcJ...,https://www.amazon.in/Redmi-Power-Black-128GB-...,4.0,965,"₹10,999","₹18,999"
1,1,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM,...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71AvQd3Vzq...,https://www.amazon.in/OnePlus-Nord-Lite-128GB-...,4.3,"113,956","₹18,999","₹19,999"
2,2,OnePlus Bullets Z2 Bluetooth Wireless in Ear E...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51UhwaQXCp...,https://www.amazon.in/Oneplus-Bluetooth-Wirele...,4.2,"90,304","₹1,999","₹2,299"
3,3,"Samsung Galaxy M33 5G (Mystique Green, 6GB, 12...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81I3w4J6yj...,https://www.amazon.in/Samsung-Mystique-Storage...,4.1,"24,863","₹15,999","₹24,999"
4,4,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71V--WZVUI...,https://www.amazon.in/OnePlus-Nord-Black-128GB...,4.3,"113,956","₹18,999","₹19,999"
...,...,...,...,...,...,...,...,...,...,...
9595,9595,PALAY® BTS Backpack For Boys Kpop BTS Bangtan ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51WpV43F1M...,https://www.amazon.in/PALAY%C2%AE-Backpack-Ban...,4.1,37,"₹1,710","₹2,491"
9596,9596,MOCA iPad Air 5th Generation Case 2022 / iPad ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/31lmoZ3XWQ...,https://www.amazon.in/MOCA-Protective-Generati...,4.2,"1,133",₹475,"₹1,999"
9597,9597,ZEBRONICS Zeb-Sound Bomb 5 TWS V5.0 Bluetooth ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61O7fCXFip...,https://www.amazon.in/Zebronics-Zeb-Sound-Blue...,3.5,"3,177",₹962,"₹3,999"
9598,9598,LINQS® Original NXP Chip | Waterproof NFC Tag ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71Sg1Qsf+4...,https://www.amazon.in/LINQS-Sticker-Smartrac-C...,3.6,210,₹400,"₹1,000"
9599,9599,Pragati Systems® Medium Grain 24x36 Inch 10 Oz...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81ozRRztsz...,https://www.amazon.in/Pragati-Systems-Stretche...,4.5,938,₹940,"₹1,120"

## data cleaning

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9600 entries, 0 to 9599
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      9600 non-null   int64
 1   name            9600 non-null   object
 2   main_category   9600 non-null   object
 3   sub_category    9600 non-null   object
 4   image           9600 non-null   object
 5   link            9600 non-null   object
 6   ratings         9505 non-null   object
 7   no_of_ratings   9505 non-null   object
 8   discount_price  9116 non-null   object
 9   actual_price    9530 non-null   object
dtypes: int64(1), object(9)
memory usage: 750.1+ KB

In [4]:
data.describe()

        Unnamed: 0
count  9600.000000
mean   4799.500000
std    2771.425626
min       0.000000
25%    2399.750000
50%    4799.500000
75%    7199.250000
max    9599.000000

In [5]:
data.head()

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,0,"Redmi 10 Power (Power Black, 8GB RAM, 128GB St...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81eM15lVcJ...,https://www.amazon.in/Redmi-Power-Black-128GB-...,4.0,965,"₹10,999","₹18,999"
1,1,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM,...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71AvQd3Vzq...,https://www.amazon.in/OnePlus-Nord-Lite-128GB-...,4.3,"113,956","₹18,999","₹19,999"
2,2,OnePlus Bullets Z2 Bluetooth Wireless in Ear E...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51UhwaQXCp...,https://www.amazon.in/Oneplus-Bluetooth-Wirele...,4.2,"90,304","₹1,999","₹2,299"
3,3,"Samsung Galaxy M33 5G (Mystique Green, 6GB, 12...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81I3w4J6yj...,https://www.amazon.in/Samsung-Mystique-Storage...,4.1,"24,863","₹15,999","₹24,999"
4,4,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71V--WZVUI...,https://www.amazon.in/OnePlus-Nord-Black-128GB...,4.3,"113,956","₹18,999","₹19,999"

In [6]:
data.tail()

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
9595,9595,PALAY® BTS Backpack For Boys Kpop BTS Bangtan ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51WpV43F1M...,https://www.amazon.in/PALAY%C2%AE-Backpack-Ban...,4.1,37,"₹1,710","₹2,491"
9596,9596,MOCA iPad Air 5th Generation Case 2022 / iPad ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/31lmoZ3XWQ...,https://www.amazon.in/MOCA-Protective-Generati...,4.2,"1,133",₹475,"₹1,999"
9597,9597,ZEBRONICS Zeb-Sound Bomb 5 TWS V5.0 Bluetooth ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61O7fCXFip...,https://www.amazon.in/Zebronics-Zeb-Sound-Blue...,3.5,"3,177",₹962,"₹3,999"
9598,9598,LINQS® Original NXP Chip | Waterproof NFC Tag ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71Sg1Qsf+4...,https://www.amazon.in/LINQS-Sticker-Smartrac-C...,3.6,210,₹400,"₹1,000"
9599,9599,Pragati Systems® Medium Grain 24x36 Inch 10 Oz...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81ozRRztsz...,https://www.amazon.in/Pragati-Systems-Stretche...,4.5,938,₹940,"₹1,120"

In [29]:
# check null values
data.isnull().sum()

Unnamed: 0          0
name                0
main_category       0
sub_category        0
image               0
link                0
ratings             0
no_of_ratings      95
discount_price    484
actual_price       70
dtype: int64

In [5]:
# fillna  - function (numpy)

In [30]:
data['no_of_ratings']=data['no_of_ratings'].fillna(0)

In [31]:
data

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,0,"Redmi 10 Power (Power Black, 8GB RAM, 128GB St...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81eM15lVcJ...,https://www.amazon.in/Redmi-Power-Black-128GB-...,False,965,"₹10,999","₹18,999"
1,1,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM,...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71AvQd3Vzq...,https://www.amazon.in/OnePlus-Nord-Lite-128GB-...,False,"113,956","₹18,999","₹19,999"
2,2,OnePlus Bullets Z2 Bluetooth Wireless in Ear E...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51UhwaQXCp...,https://www.amazon.in/Oneplus-Bluetooth-Wirele...,False,"90,304","₹1,999","₹2,299"
3,3,"Samsung Galaxy M33 5G (Mystique Green, 6GB, 12...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81I3w4J6yj...,https://www.amazon.in/Samsung-Mystique-Storage...,False,"24,863","₹15,999","₹24,999"
4,4,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71V--WZVUI...,https://www.amazon.in/OnePlus-Nord-Black-128GB...,False,"113,956","₹18,999","₹19,999"
...,...,...,...,...,...,...,...,...,...,...
9595,9595,PALAY® BTS Backpack For Boys Kpop BTS Bangtan ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51WpV43F1M...,https://www.amazon.in/PALAY%C2%AE-Backpack-Ban...,False,37,"₹1,710","₹2,491"
9596,9596,MOCA iPad Air 5th Generation Case 2022 / iPad ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/31lmoZ3XWQ...,https://www.amazon.in/MOCA-Protective-Generati...,False,"1,133",₹475,"₹1,999"
9597,9597,ZEBRONICS Zeb-Sound Bomb 5 TWS V5.0 Bluetooth ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61O7fCXFip...,https://www.amazon.in/Zebronics-Zeb-Sound-Blue...,False,"3,177",₹962,"₹3,999"
9598,9598,LINQS® Original NXP Chip | Waterproof NFC Tag ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71Sg1Qsf+4...,https://www.amazon.in/LINQS-Sticker-Smartrac-C...,False,210,₹400,"₹1,000"
9599,9599,Pragati Systems® Medium Grain 24x36 Inch 10 Oz...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81ozRRztsz...,https://www.amazon.in/Pragati-Systems-Stretche...,False,938,₹940,"₹1,120"

In [32]:
data.isnull().sum()

Unnamed: 0          0
name                0
main_category       0
sub_category        0
image               0
link                0
ratings             0
no_of_ratings       0
discount_price    484
actual_price       70
dtype: int64

In [33]:
data.duplicated().sum()

np.int64(0)

In [24]:
data['ratings']=pd.to_numeric(data['ratings']=='coerce')
data['ratings']=data['ratings'].fillna(data['ratings'].mean())

In [25]:
data

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,0,"Redmi 10 Power (Power Black, 8GB RAM, 128GB St...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81eM15lVcJ...,https://www.amazon.in/Redmi-Power-Black-128GB-...,False,965,"₹10,999","₹18,999"
1,1,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM,...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71AvQd3Vzq...,https://www.amazon.in/OnePlus-Nord-Lite-128GB-...,False,"113,956","₹18,999","₹19,999"
2,2,OnePlus Bullets Z2 Bluetooth Wireless in Ear E...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51UhwaQXCp...,https://www.amazon.in/Oneplus-Bluetooth-Wirele...,False,"90,304","₹1,999","₹2,299"
3,3,"Samsung Galaxy M33 5G (Mystique Green, 6GB, 12...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81I3w4J6yj...,https://www.amazon.in/Samsung-Mystique-Storage...,False,"24,863","₹15,999","₹24,999"
4,4,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71V--WZVUI...,https://www.amazon.in/OnePlus-Nord-Black-128GB...,False,"113,956","₹18,999","₹19,999"
...,...,...,...,...,...,...,...,...,...,...
9595,9595,PALAY® BTS Backpack For Boys Kpop BTS Bangtan ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51WpV43F1M...,https://www.amazon.in/PALAY%C2%AE-Backpack-Ban...,False,37,"₹1,710","₹2,491"
9596,9596,MOCA iPad Air 5th Generation Case 2022 / iPad ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/31lmoZ3XWQ...,https://www.amazon.in/MOCA-Protective-Generati...,False,"1,133",₹475,"₹1,999"
9597,9597,ZEBRONICS Zeb-Sound Bomb 5 TWS V5.0 Bluetooth ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61O7fCXFip...,https://www.amazon.in/Zebronics-Zeb-Sound-Blue...,False,"3,177",₹962,"₹3,999"
9598,9598,LINQS® Original NXP Chip | Waterproof NFC Tag ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71Sg1Qsf+4...,https://www.amazon.in/LINQS-Sticker-Smartrac-C...,False,210,₹400,"₹1,000"
9599,9599,Pragati Systems® Medium Grain 24x36 Inch 10 Oz...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81ozRRztsz...,https://www.amazon.in/Pragati-Systems-Stretche...,False,938,₹940,"₹1,120"

In [26]:
data.duplicated().sum()

np.int64(0)

In [34]:
data.isnull().sum()

Unnamed: 0          0
name                0
main_category       0
sub_category        0
image               0
link                0
ratings             0
no_of_ratings       0
discount_price    484
actual_price       70
dtype: int64

In [35]:
type(data)

pandas.core.frame.DataFrame

In [38]:
data['ratings'].dtype

dtype('bool')

In [39]:
data['discount_price'].dtype

dtype('O')

In [41]:
data['discount_price']=pd.to_numeric(data['discount_price']=='coerce')
data['discount_price']=data['discount_price'].fillna(data['discount_price'].mean())

In [42]:
data

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,0,"Redmi 10 Power (Power Black, 8GB RAM, 128GB St...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81eM15lVcJ...,https://www.amazon.in/Redmi-Power-Black-128GB-...,False,965,False,"₹18,999"
1,1,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM,...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71AvQd3Vzq...,https://www.amazon.in/OnePlus-Nord-Lite-128GB-...,False,"113,956",False,"₹19,999"
2,2,OnePlus Bullets Z2 Bluetooth Wireless in Ear E...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51UhwaQXCp...,https://www.amazon.in/Oneplus-Bluetooth-Wirele...,False,"90,304",False,"₹2,299"
3,3,"Samsung Galaxy M33 5G (Mystique Green, 6GB, 12...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81I3w4J6yj...,https://www.amazon.in/Samsung-Mystique-Storage...,False,"24,863",False,"₹24,999"
4,4,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71V--WZVUI...,https://www.amazon.in/OnePlus-Nord-Black-128GB...,False,"113,956",False,"₹19,999"
...,...,...,...,...,...,...,...,...,...,...
9595,9595,PALAY® BTS Backpack For Boys Kpop BTS Bangtan ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51WpV43F1M...,https://www.amazon.in/PALAY%C2%AE-Backpack-Ban...,False,37,False,"₹2,491"
9596,9596,MOCA iPad Air 5th Generation Case 2022 / iPad ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/31lmoZ3XWQ...,https://www.amazon.in/MOCA-Protective-Generati...,False,"1,133",False,"₹1,999"
9597,9597,ZEBRONICS Zeb-Sound Bomb 5 TWS V5.0 Bluetooth ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61O7fCXFip...,https://www.amazon.in/Zebronics-Zeb-Sound-Blue...,False,"3,177",False,"₹3,999"
9598,9598,LINQS® Original NXP Chip | Waterproof NFC Tag ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71Sg1Qsf+4...,https://www.amazon.in/LINQS-Sticker-Smartrac-C...,False,210,False,"₹1,000"
9599,9599,Pragati Systems® Medium Grain 24x36 Inch 10 Oz...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81ozRRztsz...,https://www.amazon.in/Pragati-Systems-Stretche...,False,938,False,"₹1,120"

In [43]:
data['discount_price'].dtype

dtype('bool')

In [44]:
data.isnull().sum()

Unnamed: 0         0
name               0
main_category      0
sub_category       0
image              0
link               0
ratings            0
no_of_ratings      0
discount_price     0
actual_price      70
dtype: int64

In [45]:
data.duplicated().sum()

np.int64(0)

In [46]:
data['actual_price']=pd.to_numeric(data['actual_price']=='coerce')
data['actual_price']=data['actual_price'].fillna(data['actual_price'].mean())

In [47]:
data

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,0,"Redmi 10 Power (Power Black, 8GB RAM, 128GB St...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81eM15lVcJ...,https://www.amazon.in/Redmi-Power-Black-128GB-...,False,965,False,False
1,1,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM,...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71AvQd3Vzq...,https://www.amazon.in/OnePlus-Nord-Lite-128GB-...,False,"113,956",False,False
2,2,OnePlus Bullets Z2 Bluetooth Wireless in Ear E...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51UhwaQXCp...,https://www.amazon.in/Oneplus-Bluetooth-Wirele...,False,"90,304",False,False
3,3,"Samsung Galaxy M33 5G (Mystique Green, 6GB, 12...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81I3w4J6yj...,https://www.amazon.in/Samsung-Mystique-Storage...,False,"24,863",False,False
4,4,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71V--WZVUI...,https://www.amazon.in/OnePlus-Nord-Black-128GB...,False,"113,956",False,False
...,...,...,...,...,...,...,...,...,...,...
9595,9595,PALAY® BTS Backpack For Boys Kpop BTS Bangtan ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51WpV43F1M...,https://www.amazon.in/PALAY%C2%AE-Backpack-Ban...,False,37,False,False
9596,9596,MOCA iPad Air 5th Generation Case 2022 / iPad ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/31lmoZ3XWQ...,https://www.amazon.in/MOCA-Protective-Generati...,False,"1,133",False,False
9597,9597,ZEBRONICS Zeb-Sound Bomb 5 TWS V5.0 Bluetooth ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61O7fCXFip...,https://www.amazon.in/Zebronics-Zeb-Sound-Blue...,False,"3,177",False,False
9598,9598,LINQS® Original NXP Chip | Waterproof NFC Tag ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71Sg1Qsf+4...,https://www.amazon.in/LINQS-Sticker-Smartrac-C...,False,210,False,False
9599,9599,Pragati Systems® Medium Grain 24x36 Inch 10 Oz...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81ozRRztsz...,https://www.amazon.in/Pragati-Systems-Stretche...,False,938,False,False

In [48]:
data.isnull().sum()

Unnamed: 0        0
name              0
main_category     0
sub_category      0
image             0
link              0
ratings           0
no_of_ratings     0
discount_price    0
actual_price      0
dtype: int64

In [49]:
data.duplicated().sum()

np.int64(0)

## Outliers

In [50]:
d1=data.copy()

In [51]:
d1

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,0,"Redmi 10 Power (Power Black, 8GB RAM, 128GB St...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81eM15lVcJ...,https://www.amazon.in/Redmi-Power-Black-128GB-...,False,965,False,False
1,1,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM,...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71AvQd3Vzq...,https://www.amazon.in/OnePlus-Nord-Lite-128GB-...,False,"113,956",False,False
2,2,OnePlus Bullets Z2 Bluetooth Wireless in Ear E...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51UhwaQXCp...,https://www.amazon.in/Oneplus-Bluetooth-Wirele...,False,"90,304",False,False
3,3,"Samsung Galaxy M33 5G (Mystique Green, 6GB, 12...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81I3w4J6yj...,https://www.amazon.in/Samsung-Mystique-Storage...,False,"24,863",False,False
4,4,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71V--WZVUI...,https://www.amazon.in/OnePlus-Nord-Black-128GB...,False,"113,956",False,False
...,...,...,...,...,...,...,...,...,...,...
9595,9595,PALAY® BTS Backpack For Boys Kpop BTS Bangtan ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51WpV43F1M...,https://www.amazon.in/PALAY%C2%AE-Backpack-Ban...,False,37,False,False
9596,9596,MOCA iPad Air 5th Generation Case 2022 / iPad ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/31lmoZ3XWQ...,https://www.amazon.in/MOCA-Protective-Generati...,False,"1,133",False,False
9597,9597,ZEBRONICS Zeb-Sound Bomb 5 TWS V5.0 Bluetooth ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61O7fCXFip...,https://www.amazon.in/Zebronics-Zeb-Sound-Blue...,False,"3,177",False,False
9598,9598,LINQS® Original NXP Chip | Waterproof NFC Tag ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71Sg1Qsf+4...,https://www.amazon.in/LINQS-Sticker-Smartrac-C...,False,210,False,False
9599,9599,Pragati Systems® Medium Grain 24x36 Inch 10 Oz...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81ozRRztsz...,https://www.amazon.in/Pragati-Systems-Stretche...,False,938,False,False

In [ ]:
# 'ratings','no_of_ratings','discount_price','actual_price'

In [52]:
Q1= d1[['ratings','no_of_ratings','discount_price','actual_price']].quantile(0.25)
Q3= d1[['ratings','no_of_ratings','discount_price','actual_price']].quantile(0.75)
IQR=Q3-Q1
print("Q1: ", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

TypeError: numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

In [53]:
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
print("Lower BOUND: ", lower_bound)
print("upper bound :", upper_bound)

NameError: name 'Q1' is not defined

In [56]:
cols=['ratings','no_of_ratings','discount_price','actual_price']
d1[cols]=d1[cols].apply(pd.to_numeric,errors='coerce')

In [58]:
q1=d1[cols].quantile(0.25)

TypeError: numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

In [60]:
cols=['ratings','no_of_ratings','discount_price','actual_price']
print(d1[cols].dtypes)

ratings              bool
no_of_ratings     float64
discount_price       bool
actual_price         bool
dtype: object

In [61]:
cols=['ratings','no_of_ratings','discount_price','actual_price']
for col in cols:
    print(f"\n{col}:")
    print(d1[col].head(10).to_list())

ratings:
[False, False, False, False, False, False, False, False, False, False]

no_of_ratings:
[965.0, nan, nan, nan, nan, 625.0, nan, nan, nan, nan]

discount_price:
[False, False, False, False, False, False, False, False, False, False]

actual_price:
[False, False, False, False, False, False, False, False, False, False]

In [62]:
cols=['ratings','no_of_ratings','discount_price','actual_price']
for col in cols:
    d1[col] = (
        d1[col]
        .astype(str)
        .str.replace(',', '', regex=False)
        .str.strip()
    )
    d1[col] = pd.to_numeric(d1[col], errors='coerce')

In [63]:
print("Data types:")
print(d1[cols].dtypes)

Data types:
ratings           float64
no_of_ratings     float64
discount_price    float64
actual_price      float64
dtype: object

In [64]:
Q1 = d1[cols].quantile(0.25)
Q3 = d1[cols].quantile(0.75)

In [65]:
IQR = Q3 - Q1

In [66]:
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
print("Lower BOUND: ", lower_bound)
print("upper bound :", upper_bound)

Lower BOUND:  ratings               NaN
no_of_ratings    -591.125
discount_price        NaN
actual_price          NaN
dtype: float64
upper bound : ratings                NaN
no_of_ratings     1141.875
discount_price         NaN
actual_price           NaN
dtype: float64

In [67]:
print("\nQ1:")
print(Q1)

print("\nQ3:")
print(Q3)

print("\nIQR:")
print(IQR)

print("\nLower Bound:")
print(lower_bound)

print("\nUpper Bound:")
print(upper_bound)
print(outliers)

Q1:
ratings             NaN
no_of_ratings     58.75
discount_price      NaN
actual_price        NaN
Name: 0.25, dtype: float64

Q3:
ratings             NaN
no_of_ratings     492.0
discount_price      NaN
actual_price        NaN
Name: 0.75, dtype: float64

IQR:
ratings              NaN
no_of_ratings     433.25
discount_price       NaN
actual_price         NaN
dtype: float64

Lower Bound:
ratings               NaN
no_of_ratings    -591.125
discount_price        NaN
actual_price          NaN
dtype: float64

Upper Bound:
ratings                NaN
no_of_ratings     1141.875
discount_price         NaN
actual_price           NaN
dtype: float64

NameError: name 'outliers' is not defined

In [68]:
for col in cols:
    outliers = d1[
        (d1[col] < lower_bound[col]) |
        (d1[col] > upper_bound[col])
    ]
    print(f"{col}: {len(outliers)} outliers")

ratings: 0 outliers
no_of_ratings: 0 outliers
discount_price: 0 outliers
actual_price: 0 outliers